I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 80, in script
    if has_industry_intro==False:
  File "game/script.rpy", line 80, in <module>
    if has_industry_intro==False:
NameError: name 'has_industry_intro' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 80, in script
    if has_industry_intro==False:
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\ast.py", line 1843, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\haapp\Desktop\Games\Ren'Py\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 80, in <module>
    if has_industry_intro==False:
NameError: name 'has_industry_intro' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.2.24090902
BubbleWitchMultiverseGame 1.0
Sat Jan 25 21:41:33 2025
